### ISSUE TITLE
Navbar isn't responsive on desktop Chrome browser

### ISSUE THREAD

**Issue by ewe2** [AhoyLemon/TheFPlus#33]
Browser is Linux Chrome Version 72.0.3626.28 (Official Build) beta (64-bit)
Issue illustrated in helpful picture: [Screenshot of site](https://i.imgur.com/fmiUdaq.png)
Navbar seems to be anchored to the bottom left and therefore cannot flow horizontally with view resizes.

**Comment by AhoyLemon** [comment]
It's possible either I'm confused on what you mean, or you're thinking the intention was to have the sidebar do something it wasn't designed to do.

At higher resolutions (770+), the sidebar takes the left 320 pixels of the screen, with the content anchored to its bottom.

**Comment by ewe2** [comment]
It just looks weird, I only understood the intent when I looked at it in chrome on my smartphone. At that resolution, there's empty space in the top left and when the mouse isn't hovering over the logo it looks cut-off. It's a minor niggle to be sure but I'm concerned about first impressions. Perhaps I've been habituated to seeing sidebars anchored to the top and not the bottom. Feel free to close the issue if you think it's not important.

**Comment by AhoyLemon** [comment]
The ballp.it comments would infer that yours is a shared opinion, but at this moment in time I'm happy with the left side nav being the way it is.
