### ISSUE TITLE
? in tag query

### ISSUE THREAD

**Issue by AhoyLemon** [AhoyLemon/TheFPlus#72]
https://ballp.it/index.php?topic=3456.msg1#new

> Tried this on both Firefox and Edge, same on both. The tag "[how in the hell did you get that fetish?](https://thefpl.us/find/tag:how%20in%20the%20hell%20did%20you%20get%20that%20fetish%3F)" doesn't advance beyond the first page. It appears that this is because on the second and third pages, it omits the question mark at the end and tries to display "[how in the hell did you get that fetish](https://thefpl.us/find/tag:how%20in%20the%20hell%20did%20you%20get%20that%20fetish/page:2)", which is not a tag. This is the only tag with a punctuation mark that is large enough to have multiple pages, tags without punctuation at the end function normally.

**Comment by eladavron** [comment]
I suspect this maya be an issue with how Kirby serves/parses urls for pagination.  
Specifically [here](https://github.com/AhoyLemon/TheFPlus/blob/ea3c279dfaeb1c34ab86d08b06b0cf6b841fab9a/kirby/vendor/getkirby/toolkit/lib/pagination.php#L194)?  
I'm can't identify the exact culprit as I'm not **that** familiar with it (nor do I have any way to really debug this?) but that might be a good place to start.
